// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANYJWQW2_Cr7mZXd32kzrMF-8IXHi5seg',
    appId: '1:697662727970:web:02f7f1f00e3bf3ccfd677b',
    messagingSenderId: '697662727970',
    projectId: 'fir-chat-35e63',
    authDomain: 'fir-chat-35e63.firebaseapp.com',
    storageBucket: 'fir-chat-35e63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbn3UZjxGf_h2JnQx4LF2m3yHp_I4YBDY',
    appId: '1:697662727970:android:95485f98eb19aa09fd677b',
    messagingSenderId: '697662727970',
    projectId: 'fir-chat-35e63',
    storageBucket: 'fir-chat-35e63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvMLCBa7me_ZG-smtlOJgCfpVM2SOkPCc',
    appId: '1:697662727970:ios:4257fe99570f7078fd677b',
    messagingSenderId: '697662727970',
    projectId: 'fir-chat-35e63',
    storageBucket: 'fir-chat-35e63.appspot.com',
    iosBundleId: 'com.example.chats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvMLCBa7me_ZG-smtlOJgCfpVM2SOkPCc',
    appId: '1:697662727970:ios:76824dd7cf59c31efd677b',
    messagingSenderId: '697662727970',
    projectId: 'fir-chat-35e63',
    storageBucket: 'fir-chat-35e63.appspot.com',
    iosBundleId: 'com.example.chats.RunnerTests',
  );
}
